name: Build and Publish Site

on:
  # allows us to run workflows manually
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout cyclus.github.com
        uses: actions/checkout@v4

      - name: Build Site
        run: |
            make docker-html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: gh-build

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/source' }}
    runs-on: ubuntu-latest
    needs: build-and-upload

    permissions:
        pages: write
        id-token: write  
    
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
 
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4